// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatfdart pub global activate flutterfire_cliorm,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print('FirebaseOptions return web ' + web.apiKey);
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2tQbNYT8aLTg1gVVrHfuHHXcYxEt9JBo',
    appId: '1:357760275644:web:9994b59f32833a52edacb9',
    messagingSenderId: '357760275644',
    projectId: 'gamer-413312',
    authDomain: 'gamer-413312.firebaseapp.com',
    storageBucket: 'gamer-413312.appspot.com',
    measurementId: 'G-057T550KX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALAL3cMwtYnKBZWHZAQy_RKmSKnja_DcQ',
    appId: '1:357760275644:android:d128f4e898538f42edacb9',
    messagingSenderId: '357760275644',
    projectId: 'gamer-413312',
    storageBucket: 'gamer-413312.appspot.com',
  );
}
